# Generated by Django 5.2 on 2025-05-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
