# Generated by Django 5.2 on 2025-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0003_user_confirm_password_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
