# Generated by Django 5.2 on 2025-06-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0004_properties_is_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
