# Generated by Django 5.2 on 2025-06-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0005_properties_gallery_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='realestateapi.properties'),
        ),
    ]
