# Generated by Django 5.2.2 on 2025-06-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0006_alter_bookings_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('CM', 'Completed'), ('CA', 'Cancelled')], default='PE', max_length=2),
        ),
    ]
