# Generated by Django 5.2.2 on 2025-06-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0009_alter_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
