# Generated by Django 5.2.2 on 2025-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0010_alter_properties_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
