# Generated by Django 5.2.2 on 2025-06-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0012_alter_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='properties/'),
        ),
    ]
