# Generated by Django 5.2.2 on 2025-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapi', '0013_alter_properties_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='gallery_images',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
